[workspace]
members = [
    "assert-owner",
    "common",
    "common/tests",
    "context",
    "dex/crank",
    "pool",
    "pool/schema",
    "pool/examples/admin-controlled",
    "pool/examples/simple",
    "cli"
]
exclude = [
    "dex",
]
